Avoid lib fix
14gasher/oauth-example pull request #15
Opened 2020-07-27 14:05 UTC by robi-van-kinobi

This small fix avoids hacking the lib directly.

Works fine for me

2020-08-14 03:15 UTC, manh-vv approved these changes

2020-09-22 14:19 UTC, 14gasher requested changes
Nice work! I would like to leave the comment in here for documentation as to why you can't use promises / async / await. If you change it and include the comment, I totally approve.

2021-03-20 00:11 UTC, AVert approved these changes

2022-06-06 15:03 UTC, NickHeap2 commented
@14gasher you should definitely get this merged in so that your example works without the hack.

2026-09-15 07:51 UTC, closed without merging